steps:
- name: "Go build and test %n"
  command: make
  plugins:
    - docker-compose#v3.7.0:
        run: app

- name: "Check licenses %n"
  command: make licensed
  plugins:
    - docker-compose#v3.7.0:
        run: licensing

- wait

- block: ":rocket: Release!"

- label: ":github: Release"
  plugins:
    - docker#v3.8.0:
        image: "goreleaser/goreleaser:v0.169.0"
        command: ["release", "--rm-dist"]
  if: build.branch == "main" && build.tag =~ /^v[0-9]+\.0\$/
  env:
      GITHUB_TOKEN: "test"
